### ISSUE TITLE
배포

### ISSUE THREAD

**Issue by wdohoon** [orlein/advanced-class-project-team-a#3]
- 배포 환경: vercel.com
- 배포 방법: 버셀이 알아서 해줌
- CI/CD: CI는 vite build, CD는 vercel
- 배포 주소: 
    - 정세윤 : https://oz-advanced-team-a.vercel.app/
    - 원도훈 : https://advanced-class-project-a.vercel.app/

**Comment by seyoonagain** [comment]
배포 주소는 강사님 레포랑 연결된 걸로 하면 될까요?
강사님 레포와 연결된 주소: https://advanced-class-project-team-a.vercel.app/

**Comment by seyoonagain** [comment]
배포 환경, 배포 방법, CI/CD를 어떻게 구별해야 할지 모르겠습니다.
vercel은 배포 방법에 속하는 걸까요?
CI/CD는 vercel에서 알아서 해주는 게 아닌지...
알려주시면 감사하겠습니다.

**Comment by seyoonagain** [comment]
제 레포와 연결된 배포 주소입니다.
https://oz-advanced-team-a.vercel.app/

**Comment by Kwonyeojiny** [comment]
제 배포 주소는 https://advanced-class-project-yeojin.vercel.app/ 
입니다
